import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { styled } from "styled-components"
import LeftHero from "@/components/leftHero"
import Intro from "@/components/intro"
import About from "@/components/aboutComp"
import RightHero from "@/components/rightHero"
import { motion } from 'framer-motion'
import { useInView } from "react-intersection-observer";
import { useEffect, useState } from "react"
import dynamic from 'next/dynamic'
 
const NoSSR = dynamic(() => import('../components/leftHero'), { ssr: false })
 


const inter = Inter({ subsets: ["latin"] })

const MainCont = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  .intro-comp {
    margin-top: 94px;
    margin-bottom: 100px;
  }
  

  .center-ref{
    margin-top: -120px;
    height: 300px;
  }

`

export default function Home() {
  const [animate,setAnimate] = useState(false);
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      setAnimate(true);
    }
    else{
      setAnimate(false);
    }
  
   
  }, [ inView]);
  return (
    <>
      <Head>
        <title>Club Excel</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/clubexcellogo.png"
        />
      </Head>
      <MainCont>
      
        <div className="Hero-div">
        <motion.div 
          transition={{ duration: 1 }}  
          animate={{opacity: animate?1:0,transform: animate?'translateX(0px)':'translateX(-300px)'}}>
                <NoSSR />
          </motion.div>

          <motion.div 
          transition={{ duration: 1 }}  
          animate={{opacity: animate?1:0,transform: animate?'translateX(0px)':'translateX(300px)'}}>
          <RightHero/>
          </motion.div>

          <div ref={ref} className="center-ref"></div>
        </div>
        <div className="bg1"></div>
          <div className="bg2"></div>
          <div className="bg3"></div>
        <div className="hero-4"></div>

        <div className="intro-comp">
          <Intro />
        </div>
        <div>
          <About />
        </div>
      </MainCont>
    </>
  )
}
