import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { styled } from "styled-components"
import LeftHero from "@/components/leftHero"
import Intro from "@/components/intro"
import About from "@/components/aboutComp"
import RightHero from "@/components/rightHero"
import { motion } from "framer-motion"
import { useInView } from "react-intersection-observer"
import { useEffect, useState } from "react"
import dynamic from "next/dynamic"
import QuickContact from "@/components/quickContact"
import WhyChoose from "@/components/whyChoose"

import { v4 as uuidv4 } from "uuid"
import Hero from "@/components/Hero"

const Carroussel = dynamic(() => import("@/components/carousel"), {
  ssr: false,
})
const Card = dynamic(() => import("@/components/Card"), {
  ssr: false,
})

const NoSSR = dynamic(() => import("../components/leftHero"), { ssr: false })

const inter = Inter({ subsets: ["latin"] })

const MainCont = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;

  .intro-comp {
    margin-top: 1094px;
    margin-bottom: 100px;
    @media (max-width: 800px) {
      margin-bottom: 0;
    }
  }
  .Hero-div {
    @media (max-width: 800px) {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
  }
.Gal-head{
  color: #fff;
    font-family: Montserrat;
    font-size: 36px;
    font-style: normal;
    font-weight: 700;
    line-height: normal;
    margin-top: 200px;
    @media (max-width: 800px) {
      margin-bottom: -50px;

    }
    @media (min-width: 801px) and (max-width: 1200px) {
    margin-top: -100px;
  }
}
 
#Gallary{
  display: flex;
  flex-direction: column;
  align-items: center;
}
`

export default function Home() {
 
  let cards = [
    {
      key: uuidv4(),
      content: <Card imagen="/p1.jpg" />,
    },
    {
      key: uuidv4(),
      content: <Card imagen="/p2.jpg" />,
    },
    {
      key: uuidv4(),
      content: <Card imagen="/p3.jpg" />,
    },
    {
      key: uuidv4(),
      content: <Card imagen="/p4.jpg" />,
    },
    {
      key: uuidv4(),
      content: <Card imagen="/p5.jpg" />,
    },
    {
      key: uuidv4(),
      content: <Card imagen="/p6.jpg" />,
    },
  ]

  return (
    <>
      <Head>
        <title>Club Excel</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/clubexcellogo.png"
        />
      </Head>
      <MainCont>
          <Hero/>
        <div
                 id="about"
                 >
          <QuickContact />
        </div>

        <div className="bg1"></div>
        <div className="bg2" ></div>
        <div className="bg3"></div>
        <div className="hero-4"></div>

        <div
          className="intro-comp"
        >
          <Intro />
        </div>
        <div   >
          <About />
        </div>
        <div>
          <WhyChoose />
        </div>
        <div id="Gallary">
          <div className="Gal-head">Gallary</div>
          <Carroussel
            cards={cards}
            height="500px"
            width="50%"
            margin="0 auto"
            offset={2}
            showArrows={false}
          />
        </div>
      </MainCont>
    </>
  )
}
