import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { styled } from "styled-components"
import LeftHero from "@/components/leftHero"
import Intro from "@/components/intro"
import About from "@/components/aboutComp"
import RightHero from "@/components/rightHero"
import { motion } from "framer-motion"
import { useInView } from "react-intersection-observer"
import { useEffect, useState } from "react"
import dynamic from "next/dynamic"
import QuickContact from "@/components/quickContact"
import WhyChoose from "@/components/whyChoose"
import Gallary from "@/components/Gallary"
import { v4 as uuidv4 } from "uuid"

const Carroussel = dynamic(() => import("@/components/carousel"), {
  ssr: false,
})
const Card = dynamic(() => import("@/components/Card"), {
  ssr: false,
})

const NoSSR = dynamic(() => import("../components/leftHero"), { ssr: false })

const inter = Inter({ subsets: ["latin"] })

const MainCont = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  .intro-comp {
    margin-top: 94px;
    margin-bottom: 100px;
  }

  .center-ref {
    margin-top: -120px;
    height: 300px;
  }
`

export default function Home() {
  const [animate, setAnimate] = useState(false)
  const [ref, inView] = useInView()
  let cards = [
    {
      key: uuidv4(),
      content: <Card imagen="/club excel image.jpg" />,
    },
    {
      key: uuidv4(),
      content: (
        <Card imagen="https://updates.theme-fusion.com/wp-content/uploads/2017/12/acf_pro.png" />
      ),
    },
    {
      key: uuidv4(),
      content: (
        <Card imagen="https://updates.theme-fusion.com/wp-content/uploads/2017/12/layer_slider_plugin_thumb.png" />
      ),
    },
    {
      key: uuidv4(),
      content: (
        <Card imagen="https://updates.theme-fusion.com/wp-content/uploads/2016/08/slider_revolution-1.png" />
      ),
    },
    {
      key: uuidv4(),
      content: (
        <Card imagen="https://updates.theme-fusion.com/wp-content/uploads/2019/01/pwa_880_660.jpg" />
      ),
    },
  ]
  useEffect(() => {
    if (inView) {
      setAnimate(true)
    } else {
      setAnimate(false)
    }
  }, [inView])
  return (
    <>
      <Head>
        <title>Club Excel</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/clubexcellogo.png"
        />
      </Head>
      <MainCont>
        <div className="Hero-div">
          <motion.div
            transition={{ duration: 1 }}
            animate={{
              opacity: animate ? 1 : 0,
              transform: animate ? "translateX(0px)" : "translateX(-300px)",
            }}
          >
            <NoSSR />
          </motion.div>

          <motion.div
            transition={{ duration: 1 }}
            animate={{
              opacity: animate ? 1 : 0,
              transform: animate ? "translateX(0px)" : "translateX(300px)",
            }}
          >
            <RightHero />
          </motion.div>

          <div
            ref={ref}
            className="center-ref"
          ></div>
        </div>
        <div>
          <QuickContact />
        </div>

        <div className="bg1"></div>
        <div className="bg2"></div>
        <div className="bg3"></div>
        <div className="hero-4"></div>

        <div className="intro-comp">
          <Intro />
        </div>
        <div>
          <About />
        </div>
        <div>
          <WhyChoose />
        </div>
        <div>
          <Carroussel
            cards={cards}
            height="500px"
            width="50%"
            margin="0 auto"
            offset={2}
            showArrows={false}
          />
        </div>
      </MainCont>
    </>
  )
}
